############################################################################
# Contest 2026 team 072 - MindFlow Agent App - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = mindflow
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_EXAMPLES_MINDFLOW_AGENT)

MAINSRC = mindflow_main.c
CSRCS   = mindflow_audio.c

include $(APPDIR)/Application.mk
